local M = {}

function M.get(c, opts)
  local bg = opts.transparent and c.none or c.bg
  local float_bg = opts.transparent and c.none or c.bg_float

  return {
    Normal = { fg = c.fg, bg = bg },
    NormalNC = { fg = c.fg, bg = bg },
    NormalFloat = { fg = c.fg, bg = float_bg },
    FloatBorder = { fg = c.border, bg = float_bg },
    FloatTitle = { fg = c.olive_bright, bg = float_bg, bold = true },
    FloatFooter = { fg = c.muted, bg = float_bg },
    ColorColumn = { bg = c.bg_alt },
    Conceal = { fg = c.subtle },
    Cursor = { fg = c.bg, bg = c.cursor },
    lCursor = { fg = c.bg, bg = c.cursor },
    CursorIM = { fg = c.bg, bg = c.cursor },
    CursorColumn = { bg = c.bg_alt },
    CursorLine = { bg = c.bg_alt },
    CursorLineNr = { fg = c.fg, bold = true },
    LineNr = { fg = c.subtle },
    Directory = { fg = c.teal, bold = true },
    EndOfBuffer = { fg = c.bg },
    ErrorMsg = { fg = c.red, bold = true },
    WarningMsg = { fg = c.amber, bold = true },
    MoreMsg = { fg = c.olive, bold = true },
    ModeMsg = { fg = c.olive_bright, bold = true },
    Folded = { fg = c.muted, bg = c.bg_alt },
    FoldColumn = { fg = c.subtle },
    SignColumn = { fg = c.subtle, bg = bg },
    IncSearch = { fg = c.bg, bg = c.search_current, bold = true },
    CurSearch = { fg = c.bg, bg = c.search_current, bold = true },
    Search = { fg = c.bg, bg = c.search, bold = true },
    MatchParen = { fg = c.fg, bg = c.selection, bold = true },
    NonText = { fg = c.subtle },
    Pmenu = { fg = c.fg, bg = float_bg },
    PmenuSel = { fg = c.bg, bg = c.olive_bright, bold = true },
    PmenuSbar = { bg = c.bg_alt },
    PmenuThumb = { bg = c.border },
    Question = { fg = c.teal, bold = true },
    QuickFixLine = { bg = c.selection, bold = true },
    SpecialKey = { fg = c.subtle },
    SpellBad = { sp = c.red, undercurl = true },
    SpellCap = { sp = c.amber, undercurl = true },
    SpellLocal = { sp = c.teal, undercurl = true },
    SpellRare = { sp = c.violet, undercurl = true },
    StatusLine = { fg = c.fg, bg = c.bg_statusline },
    StatusLineNC = { fg = c.muted, bg = c.bg_alt },
    StatusLineTerm = { fg = c.fg, bg = c.bg_statusline },
    StatusLineTermNC = { fg = c.muted, bg = c.bg_alt },
    Substitute = { fg = c.bg, bg = c.amber, bold = true },
    TabLine = { fg = c.muted, bg = c.bg_alt },
    TabLineFill = { bg = c.bg_alt },
    TabLineSel = { fg = c.fg, bg = c.bg_statusline, bold = true },
    Title = { fg = c.olive, bold = true },
    Visual = { bg = c.bg_visual },
    VisualNOS = { bg = c.selection },
    Whitespace = { fg = c.subtle },
    WildMenu = { fg = c.bg, bg = c.teal, bold = true },
    WinBar = { fg = c.fg_alt, bg = c.bg_alt },
    WinBarNC = { fg = c.muted, bg = c.bg_alt },
    WinSeparator = { fg = c.border, bg = bg },
  }
end

return M
