local M = {}

function M.get(c, opts)
  return {
    Comment = vim.tbl_extend('force', { fg = c.muted }, opts.styles.comments or {}),
    Constant = { fg = c.sand },
    String = vim.tbl_extend('force', { fg = c.cyan }, opts.styles.strings or {}),
    Character = { fg = c.cyan },
    Number = { fg = c.sand },
    Boolean = { fg = c.violet },
    Float = { fg = c.sand },
    Identifier = vim.tbl_extend('force', { fg = c.fg_alt }, opts.styles.variables or {}),
    Function = vim.tbl_extend('force', { fg = c.rust }, opts.styles.functions or {}),
    Statement = { fg = c.olive },
    Conditional = { fg = c.olive },
    Repeat = { fg = c.olive },
    Label = { fg = c.olive },
    Operator = { fg = c.fg_alt },
    Keyword = vim.tbl_extend('force', { fg = c.olive }, opts.styles.keywords or {}),
    Exception = { fg = c.rust },
    PreProc = { fg = c.rust },
    Include = { fg = c.rust },
    Define = { fg = c.rust },
    Macro = { fg = c.rust },
    PreCondit = { fg = c.rust },
    Type = { fg = c.cyan },
    StorageClass = { fg = c.cyan },
    Structure = { fg = c.cyan },
    Typedef = { fg = c.cyan },
    Special = { fg = c.rust },
    SpecialChar = { fg = c.cyan },
    Tag = { fg = c.teal },
    Delimiter = { fg = c.subtle },
    Debug = { fg = c.red },
    Underlined = { fg = c.cyan, underline = true },
    Ignore = { fg = c.subtle },
    Error = { fg = c.red, bg = c.error_bg, bold = true },
    Todo = { fg = c.bg, bg = c.search_current, bold = true },
    Added = { fg = c.olive_bright },
    Changed = { fg = c.amber },
    Removed = { fg = c.red },
    DiffAdd = { fg = c.olive_bright, bg = c.diff_add },
    DiffChange = { fg = c.amber, bg = c.diff_change },
    DiffDelete = { fg = c.red, bg = c.diff_delete },
    DiffText = { fg = c.fg, bg = c.diff_text, bold = true },
  }
end

return M
